stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model.pkl
    - src/model_evaluation.py
    metrics:
    - metrics.json
